"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type View = "Dashboard" | "Screener" | "Company Detail" | "Watchlist" | "Data Pilot";
type Company = { ticker:string; company:string; sector:string; status:"Newly Selected"|"Continuing Improvement"|"Watch"; reason:string };
const companies: Company[] = [
  {ticker:"PLTR",company:"Palantir Technologies",sector:"Technology · Software",status:"Newly Selected",reason:"Screening logic: 데이터 누적 후 확정"},
  {ticker:"NVDA",company:"NVIDIA Corporation",sector:"Technology · Semiconductors",status:"Continuing Improvement",reason:"Screening logic: 데이터 누적 후 확정"},
  {ticker:"MSFT",company:"Microsoft Corporation",sector:"Technology · Software",status:"Watch",reason:"Screening logic: 데이터 누적 후 확정"},
];
const icons:Record<View,string>={Dashboard:"⌂",Screener:"◎","Company Detail":"▤",Watchlist:"☆","Data Pilot":"↻"};

export default function Home(){
  const [view,setView]=useState<View>("Dashboard"); const [ticker,setTicker]=useState("PLTR"); const [mobile,setMobile]=useState(false); const pilot=usePilot();
  const open=(next:string)=>{setTicker(next);setView("Company Detail");setMobile(false)};
  return <main className="structure-shell"><aside className={`main-nav ${mobile?"open":""}`}><div className="nav-brand"><span>F</span><div><strong>Fundamental Flow</strong><small>Investment Philosophy v1.1</small></div></div><nav aria-label="주요 화면">{(Object.keys(icons) as View[]).map(item=><button key={item} className={view===item?"active":""} onClick={()=>{setView(item);setMobile(false)}}><i>{icons[item]}</i><span>{item}</span>{item==="Data Pilot"&&<b>LIVE</b>}</button>)}</nav><div className="nav-philosophy"><span>OUR PHILOSOPHY</span><p>우리는 주가를 추종하지 않는다.<br/><strong>기업의 변화를 추적한다.</strong></p></div><div className="pilot-indicator"><i/> Pilot Universe: 3 / Nasdaq 100</div></aside>
    <section className="structure-workspace"><header className="structure-header"><button className="menu-button" onClick={()=>setMobile(!mobile)} aria-label="메뉴 열기">☰</button><div><span>{view}</span><small>Actual Growth · FY1 Consensus</small></div><button className="header-search" onClick={()=>setView("Screener")}>⌕ <span>기업 검색</span></button></header>
      {view==="Dashboard"&&<Dashboard pilot={pilot} open={open}/>} {view==="Screener"&&<Screener pilot={pilot} open={open}/>} {view==="Company Detail"&&<Detail pilot={pilot} ticker={ticker}/>} {view==="Watchlist"&&<Watchlist open={open}/>} {view==="Data Pilot"&&<DataPilot pilot={pilot} open={open}/>}</section>{mobile&&<button className="nav-overlay" aria-label="메뉴 닫기" onClick={()=>setMobile(false)}/>}</main>;
}

function Dashboard({pilot,open}:{pilot:PilotState;open:(t:string)=>void}){
  const cards=[{label:"신규 선정",value:1,tone:"blue"},{label:"지속 개선",value:1,tone:"green"},{label:"관찰",value:1,tone:"amber"},{label:"주의",value:0,tone:"red"},{label:"제외",value:0,tone:"gray"}];
  return <div className="structure-content"><section className="structure-hero"><div><span>NASDAQ 100 · FUNDAMENTAL CHANGE</span><h1>실제 성장과 미래 전망을<br/>분리해 추적합니다</h1><p>최근 분기 EPS·Revenue YoY와 가장 가까운 미래 회계연도의 FY1 EPS 컨센서스를 동일한 정의로 관리합니다.</p></div><div className="universe-ring"><strong>3</strong><span>PILOT COMPANIES</span><small>of Nasdaq 100</small></div></section><LiveBanner pilot={pilot}/><div className="status-card-grid">{cards.map(c=><article key={c.label} className={`status-card ${c.tone}`}><span>{c.label}</span><strong>{c.value}</strong><small>분류 규칙 준비 중</small></article>)}</div>
    <section className="structure-panel"><Panel eyebrow="ACTUAL GROWTH" title="기업 현황" badge={originLabel(pilot)}/><div className="company-summary-list growth-summary">{companies.map(c=>{const s=find(pilot.snapshots,c.ticker);return <button key={c.ticker} onClick={()=>open(c.ticker)}><span className="ticker-avatar">{c.ticker.slice(0,2)}</span><div><strong>{c.ticker}</strong><small>{c.company}</small></div><Status status={c.status}/><div className="summary-signal"><b>최근 분기 EPS {formatEps(num(s,"latest_quarter_eps","latestQuarterEps"))}</b><small className={toneClass(epsTone(s))}>{epsYoyText(s)}</small><small className={`revenue-line ${toneClass(num(s,"revenue_yoy_pct","revenueYoyPct"))}`}>Revenue {yoy(num(s,"revenue_yoy_pct","revenueYoyPct"))}</small></div><i>›</i></button>})}</div></section></div>;
}

function Screener({pilot,open}:{pilot:PilotState;open:(t:string)=>void}){
  const [query,setQuery]=useState(""); const [filter,setFilter]=useState("all"); const [sort,setSort]=useState("eps_yoy");
  const visible=useMemo(()=>companies.map(company=>({company,s:find(pilot.snapshots,company.ticker)})).filter(({company,s})=>`${company.ticker} ${company.company}`.toLowerCase().includes(query.toLowerCase())&&(filter==="all"||(filter==="turnaround"&&str(s,"eps_yoy_status","epsYoyStatus")==="profit_turnaround")||(filter==="fy1_up"&&((num(s,"fwd_eps_change_pct","fy1EpsChange1mPct")??0)>0||(num(s,"fy1_eps_change_3m_pct","fy1EpsChange3mPct")??0)>0)))).sort((a,b)=>metric(b.s,sort)-metric(a.s,sort)),[query,filter,sort,pilot.snapshots]);
  return <div className="structure-content"><Heading eyebrow="SCREENING WORKSPACE" title="Screener" description="실제 성장과 미래 컨센서스를 분리해 비교합니다. 선정 기준과 가중치는 데이터 축적 후 확정합니다." badge={originLabel(pilot)}/><div className="filter-bar advanced"><label><span>⌕</span><input aria-label="기업 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="티커 또는 회사명 검색"/></label><select aria-label="상태 필터" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체 기업</option><option value="turnaround">흑자 전환 기업</option><option value="fy1_up">FY1 EPS 상향 기업</option></select><select aria-label="정렬" value={sort} onChange={e=>setSort(e.target.value)}><option value="eps_yoy">EPS YoY 높은 순</option><option value="revenue_yoy">Revenue YoY 높은 순</option><option value="fy1_1m">FY1 EPS 1개월 수정률 높은 순</option><option value="fy1_3m">FY1 EPS 3개월 수정률 높은 순</option></select><span>{visible.length} companies</span></div>
    <section className="structure-panel screener-table"><table><thead><tr><th>상태</th><th>기업</th><th>최근 분기 EPS</th><th>최근 분기 Revenue</th><th>FY1 EPS 추세</th><th>선정·제외 이유</th><th>데이터</th></tr></thead><tbody>{visible.map(({company:c,s})=><tr key={c.ticker} onClick={()=>open(c.ticker)}><td><Status status={c.status}/></td><td><strong>{c.ticker}</strong><small>{c.company}</small></td><MetricCell value={formatEps(num(s,"latest_quarter_eps","latestQuarterEps"))} sub={epsYoyText(s)} tone={epsTone(s)}/><MetricCell value={formatMoney(num(s,"latest_quarter_revenue","latestQuarterRevenue"))} sub={yoy(num(s,"revenue_yoy_pct","revenueYoyPct"))} tone={num(s,"revenue_yoy_pct","revenueYoyPct")}/><MetricCell value={`${formatEps(fy1Eps(s))} · ${fy1Label(s)}`} sub={fy1Sub(s)} tone={fy1Change3m(s)}/><td>{c.reason}<small>최종 가중치 준비 중</small></td><td><DataBadge pilot={pilot} snapshot={s}/></td></tr>)}</tbody></table></section></div>;
}

function Detail({pilot,ticker}:{pilot:PilotState;ticker:string}){
  const c=companies.find(x=>x.ticker===ticker)??companies[0],s=find(pilot.snapshots,ticker),companyHistory=useCompanyHistory(ticker),history=companyHistory.rows.filter(x=>fy1Eps(x)!==null&&fy1Label(x)===fy1Label(s)).slice().reverse();
  const period=`${str(s,"latest_fiscal_year","latestFiscalYear")??"—"} ${str(s,"latest_fiscal_period","latestFiscalPeriod")??""}`;
  return <div className="structure-content"><section className="detail-heading"><div className="ticker-avatar large">{c.ticker.slice(0,2)}</div><div><span>{c.sector}</span><h1>{c.company}</h1><p>{c.ticker} · Nasdaq 100 Pilot</p></div><Status status={c.status}/></section><div className="detail-section-grid">
    <section className="structure-panel wide"><Panel eyebrow="COMPANY PROFILE" title="기업 기본 정보" badge="PILOT"/><div className="profile-grid"><span>티커<strong>{c.ticker}</strong></span><span>회사명<strong>{c.company}</strong></span><span>섹터<strong>{c.sector}</strong></span><span>데이터 상태<strong>{snapshotState(pilot,s)}</strong></span></div></section>
    <section className="structure-panel connected-section wide"><Panel eyebrow="ACTUAL RESULTS · GAAP" title="Raw Data" badge={s?"LIVE":"데이터 없음"}/><div className="connected-metrics result-cards"><ResultCard label="최근 분기 EPS" value={formatEps(num(s,"latest_quarter_eps","latestQuarterEps"))} change={epsYoyText(s)} period={period} tone={epsTone(s)}/><ResultCard label="최근 분기 Revenue" value={formatMoney(num(s,"latest_quarter_revenue","latestQuarterRevenue"))} change={yoy(num(s,"revenue_yoy_pct","revenueYoyPct"))} period={period} tone={num(s,"revenue_yoy_pct","revenueYoyPct")}/><ResultCard label="EPS 증감액" value={formatSignedEps(num(s,"eps_change_amount","epsChangeAmount"))} change="전년 동일 회계분기 대비" period={str(s,"latest_period_end","latestPeriodEnd")??"—"} tone={num(s,"eps_change_amount","epsChangeAmount")}/></div></section>
    <section className="structure-panel connected-section wide"><Panel eyebrow="FORWARD FISCAL YEAR CONSENSUS" title="미래 전망" badge={fy1Eps(s)===null?"산출 불가":"LIVE"}/><div className="forecast-layout"><div className="ntm-hero"><span>FY1 EPS</span><strong>{formatEps(fy1Eps(s))}</strong><p>{fy1Label(s)} · 가장 가까운 미래 회계연도</p></div><div className="revision-list"><MetricLine label="1개월 수정률" value={revision(fy1Change1m(s))}/><MetricLine label="3개월 수정률" value={revision(fy1Change3m(s))}/><MetricLine label="추세" value={trendText(s)}/></div></div><p className="connection-message">수정률은 동일한 대상 회계연도의 FY1 EPS끼리만 비교합니다. 기준 연도가 바뀌면 새 시계열로 시작합니다.</p></section>
    <section className="structure-panel guidance-section wide"><Panel eyebrow="MANAGEMENT INTENT" title="Management Guidance" badge="COMING SOON"/><div className="guidance-grid"><article><span>REVENUE GUIDANCE</span><strong>매출 가이던스</strong><p>경영진이 제시한 매출 전망의 방향과 시장 기대 수준을 분리해 봅니다.</p><div className="guidance-comparisons"><small>이전 경영진 가이던스 대비<b>연결 예정</b></small><small>시장 컨센서스 대비<b>연결 예정</b></small></div></article><article><span>EARNINGS OUTLOOK</span><strong>이익·마진 전망</strong><p>EPS와 영업이익률에 대한 공식 전망을 서로 다른 비교 기준으로 확인합니다.</p><div className="guidance-comparisons"><small>이전 마진 전망 대비<b>연결 예정</b></small><small>시장 EPS 컨센서스 대비<b>연결 예정</b></small></div></article><article><span>CAPITAL ALLOCATION</span><strong>CAPEX 방향</strong><p>투자 확대·유지·축소 여부와 경영진이 설명한 목적을 함께 확인합니다.</p><div className="guidance-comparisons"><small>이전 투자계획 대비<b>연결 예정</b></small><small>FCF 영향 판단<b>연결 예정</b></small></div></article></div><div className="call-ai-preview"><div><span>EARNINGS CALL AI OPINION</span><strong>컨콜 AI 의견</strong></div><p>지난 분기보다 경영진이 더 낙관적인지, 보수적인지 또는 변화가 없는지를 짧게 요약합니다.</p><b>AI 연결 전 · Coming Soon</b></div></section>
    <section className="structure-panel wide"><Panel eyebrow="TIME SERIES" title="Monthly Trends" badge={companyHistory.loading?"불러오는 중":history.length>=2?"LIVE":"준비 중"}/>{history.length>=2?<div className="trend-chart" aria-label="FY1 EPS 월별 추세">{history.map((x,i)=><div key={`${x.ticker}-${i}`} style={{height:`${Math.max(18,(fy1Eps(x)??0)/Math.max(...history.map(h=>fy1Eps(h)??1))*100)}%`}} title={`${str(x,"snapshot_date","snapshotDate")}: ${formatEps(fy1Eps(x))}`}/>)}</div>:<div className="empty-state"><strong>{companyHistory.loading?"스냅샷 이력 불러오는 중":"FY1 EPS 추세 준비 중"}</strong><span>{fy1Label(s)} 기준 최소 2개 유효 월별 스냅샷 필요 · 현재 {history.length}개</span></div>}<SnapshotHistory rows={companyHistory.rows} loading={companyHistory.loading}/></section>
    <section className="structure-panel wide"><Panel eyebrow="CLASSIFICATION" title="Screening Status" badge="준비 중"/><div className="empty-state"><strong>네 가지 핵심 지표 데이터 축적 중</strong><span>EPS YoY · Revenue YoY · FY1 1M · FY1 3M</span></div></section></div>
    <section className="abbreviation-guide"><span>약어 안내</span><Abbr short="EPS" full="Earnings per Share" ko="주당순이익"/><Abbr short="YoY" full="Year over Year" ko="전년 동기 대비"/><Abbr short="FY1" full="Forward Fiscal Year 1" ko="가장 가까운 미래 회계연도"/><Abbr short="FCF" full="Free Cash Flow" ko="잉여현금흐름"/></section></div>;
}

function Watchlist({open}:{open:(t:string)=>void}){return <div className="structure-content"><Heading eyebrow="PERSONAL MONITORING" title="Watchlist" description="저장 기능을 연결하기 전 샘플 관심기업 화면입니다. 실제 포트폴리오가 아닙니다." badge="SAMPLE"/><div className="watchlist-grid">{companies.slice(0,2).map(c=><button key={c.ticker} onClick={()=>open(c.ticker)}><span className="ticker-avatar">{c.ticker.slice(0,2)}</span><div><strong>{c.ticker}</strong><p>{c.company}</p></div><small>SAMPLE · 저장되지 않음</small></button>)}</div></div>}

function DataPilot({pilot,open}:{pilot:PilotState;open:(ticker:string)=>void}){const missing=pilot.snapshots.filter(s=>missingList(read(s,"missing_fields","missingFields")).length).length;return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">F</span><span>Fundamental Flow</span><span className="mvp-badge">FMP PILOT</span></div><span className={`api-pill ${pilot.status}`}><i/>{statusLabel[pilot.status]}</span></header><section className="content"><div className="hero-row"><div><p className="eyebrow">ACTUAL GROWTH · FY1 CONSENSUS</p><h1>재무 데이터 API 파일럿</h1><p className="subtitle">기업별 최신 수집 상태를 관리합니다. 과거 스냅샷은 각 기업의 이력 보기에서 확인합니다.</p></div><button className="sync-button" onClick={pilot.refresh} disabled={pilot.refreshing||pilot.status==="key_missing"}><span className={pilot.refreshing?"spinning":""}>↻</span>{pilot.refreshing?"수집 중…":"지금 업데이트"}</button></div>
    <section className="connection-panel"><div className="connection-main"><span className={`connection-icon ${pilot.snapshots.length?"live":""}`}>{pilot.snapshots.length?"✓":"!"}</span><div><strong>Financial Modeling Prep</strong><p>{statusLabel[pilot.status]} · 서버 측 보안 연결</p></div></div><div className="connection-stat"><span>테스트 유니버스</span><strong>3개 종목</strong></div><div className="connection-stat"><span>마지막 업데이트</span><strong>{dateTime(pilot.lastUpdated)}</strong></div><div className="connection-stat"><span>데이터 누락</span><strong>{missing}개 기업</strong></div></section>
    {pilot.status==="error"&&<div className="notice-banner"><strong>API 오류</strong><span>마지막 정상 스냅샷: {dateTime(pilot.lastSuccessfulUpdate)}</span></div>}
    <div className="metric-grid compact-metrics"><Info label="실제 EPS" value="GAAP Diluted" note="동일 회계분기 YoY"/><Info label="실제 Revenue" value="Quarterly" note="동일 회계분기 YoY"/><Info label="미래 전망" value="FY1 EPS" note="가장 가까운 미래 회계연도"/><Info label="금액 단위" value="$B / $M" note="달러 단위 일관 표시"/></div>
    <section className="table-card"><div className="result-bar live-result"><div><strong>기업별 최신 스냅샷</strong><span>{originLabel(pilot)}</span></div><span>전체 이력은 기업별로 분리 조회</span></div><div className="table-scroll"><table className="fundamental-table growth-table"><thead><tr><th>기업</th><th>최신 스냅샷</th><th>최근 실적 회계분기</th><th>최근 분기 EPS</th><th>EPS YoY</th><th>최근 분기 Revenue</th><th>Revenue YoY</th><th>FY1 EPS</th><th>대상 연도</th><th>FY1 1M</th><th>FY1 3M</th><th>품질</th><th>이력</th></tr></thead><tbody>{pilot.snapshots.map(s=><PilotRow key={s.ticker} s={s} open={open}/>)}</tbody></table>{!pilot.snapshots.length&&<div className="empty-state table-empty"><strong>{pilot.status==="loading"?"불러오는 중":"데이터 없음"}</strong><span>LIVE 데이터가 로드된 후에만 값과 성장률을 표시합니다.</span></div>}</div></section>
    <section className="definition-card"><div><span>01</span><strong>Actual EPS</strong><p>FMP GAAP diluted EPS, 동일 회계분기 비교</p></div><div><span>02</span><strong>Revenue YoY</strong><p>최근 분기와 전년 동일 분기의 매출 비교</p></div><div><span>03</span><strong>FY1 EPS</strong><p>현재 이후 가장 가까운 회계연도의 annual epsAvg</p></div><div><span>04</span><strong>Revisions</strong><p>동일 FY1 대상 연도의 1개월·3개월 저장값과 비교</p></div></section></section></main>}

function PilotRow({s,open}:{s:Snapshot;open:(ticker:string)=>void}){const missing=missingList(read(s,"missing_fields","missingFields"));return <tr><td><div className="company-cell"><span className="ticker">{s.ticker}</span><strong>{companies.find(c=>c.ticker===s.ticker)?.company}</strong></div></td><td>{str(s,"snapshot_date","snapshotDate")??"—"}</td><td>{`${str(s,"latest_fiscal_year","latestFiscalYear")??"—"} ${str(s,"latest_fiscal_period","latestFiscalPeriod")??""}`}</td><td>{formatEps(num(s,"latest_quarter_eps","latestQuarterEps"))}</td><td className={toneClass(epsTone(s))}>{epsYoyText(s)}</td><td>{formatMoney(num(s,"latest_quarter_revenue","latestQuarterRevenue"))}</td><td className={toneClass(num(s,"revenue_yoy_pct","revenueYoyPct"))}>{yoy(num(s,"revenue_yoy_pct","revenueYoyPct"))}</td><td>{formatEps(fy1Eps(s))}</td><td>{fy1Label(s)}</td><td>{revision(fy1Change1m(s))}</td><td>{revision(fy1Change3m(s))}</td><td><span className={`quality-badge ${missing.length?"partial":"complete"}`}>{missing.length?`부분 · ${missing.length}개 산출 불가`:"완전"}</span></td><td><button className="history-button" onClick={()=>open(s.ticker)} aria-label={`${s.ticker} 스냅샷 이력 보기`}>이력 보기 ›</button></td></tr>}

type ApiStatus="loading"|"connected"|"partial"|"key_missing"|"database_error"|"database_unavailable"|"error";
type Snapshot={ticker:string;[key:string]:unknown};
type PilotState={status:ApiStatus;snapshots:Snapshot[];history:Snapshot[];lastUpdated:string|null;lastSuccessfulUpdate:string|null;refreshing:boolean;refresh:()=>Promise<void>};
const statusLabel:Record<ApiStatus,string>={loading:"불러오는 중",connected:"LIVE",partial:"LIVE · 일부 산출 불가",key_missing:"API 키 필요",database_error:"오류",database_unavailable:"데이터 없음",error:"오류"};

function usePilot():PilotState{const [status,setStatus]=useState<ApiStatus>("loading"),[snapshots,setSnapshots]=useState<Snapshot[]>([]),[history,setHistory]=useState<Snapshot[]>([]),[lastUpdated,setLastUpdated]=useState<string|null>(null),[lastSuccessfulUpdate,setLastSuccessful]=useState<string|null>(null),[refreshing,setRefreshing]=useState(false);const load=useCallback(async()=>{try{const r=await fetch("/api/fundamentals",{cache:"no-store"}),p=await r.json();setStatus((p.status as ApiStatus)||(r.ok?"connected":"error"));setSnapshots(Array.isArray(p.snapshots)?p.snapshots:[]);setHistory(Array.isArray(p.history)?p.history:[]);setLastUpdated(p.lastUpdated??null);setLastSuccessful(p.lastSuccessfulUpdate??null)}catch{setStatus("error")}},[]);useEffect(()=>{queueMicrotask(()=>void load())},[load]);const refresh=useCallback(async()=>{setRefreshing(true);try{const r=await fetch("/api/fundamentals",{method:"POST"}),p=await r.json();setStatus((p.status as ApiStatus)||(r.ok?"connected":"error"));if(Array.isArray(p.results))setSnapshots(p.results);setLastUpdated(p.lastUpdated??null);await load()}catch{setStatus("error")}finally{setRefreshing(false)}},[load]);return{status,snapshots,history,lastUpdated,lastSuccessfulUpdate,refreshing,refresh}}

function useCompanyHistory(ticker:string){const [state,setState]=useState<{ticker:string;rows:Snapshot[]}>({ticker:"",rows:[]});useEffect(()=>{let active=true;fetch(`/api/fundamentals?ticker=${encodeURIComponent(ticker)}`,{cache:"no-store"}).then(r=>r.json()).then(p=>{if(active)setState({ticker,rows:Array.isArray(p.history)?p.history:[]})}).catch(()=>{if(active)setState({ticker,rows:[]})});return()=>{active=false}},[ticker]);return{rows:state.ticker===ticker?state.rows:[],loading:state.ticker!==ticker}}

function SnapshotHistory({rows,loading}:{rows:Snapshot[];loading:boolean}){return <div className="snapshot-history"><div className="history-heading"><div><span>SNAPSHOT HISTORY</span><strong>저장 이력</strong></div><b>{loading?"불러오는 중":`${rows.length}개 기록`}</b></div>{!loading&&rows.length?<div className="history-scroll"><table><thead><tr><th>저장일</th><th>대상 연도</th><th>FY1 EPS</th><th>1M 수정률</th><th>3M 수정률</th><th>최근 분기 EPS YoY</th><th>Revenue YoY</th><th>품질</th></tr></thead><tbody>{rows.map((row,index)=><tr key={`${str(row,"snapshot_date","snapshotDate")}-${index}`}><td>{str(row,"snapshot_date","snapshotDate")??"—"}</td><td>{fy1Label(row)}</td><td>{formatEps(fy1Eps(row))}</td><td>{revision(fy1Change1m(row))}</td><td>{revision(fy1Change3m(row))}</td><td className={toneClass(epsTone(row))}>{epsYoyText(row)}</td><td className={toneClass(num(row,"revenue_yoy_pct","revenueYoyPct"))}>{yoy(num(row,"revenue_yoy_pct","revenueYoyPct"))}</td><td><span className={`quality-badge ${missingList(read(row,"missing_fields","missingFields")).length?"partial":"complete"}`}>{missingList(read(row,"missing_fields","missingFields")).length?"부분":"완전"}</span></td></tr>)}</tbody></table></div>:!loading?<div className="empty-state"><strong>저장된 스냅샷이 없습니다.</strong><span>Data Pilot에서 업데이트하면 날짜별로 저장됩니다.</span></div>:null}</div>}

const read=(s:Snapshot|null,a:string,b:string)=>s?.[a]??s?.[b]??null;
const num=(s:Snapshot|null,a:string,b:string)=>{const v=read(s,a,b);return typeof v==="number"?v:null};
const str=(s:Snapshot|null,a:string,b:string)=>{const v=read(s,a,b);return typeof v==="string"?v:null};
const find=(rows:Snapshot[],ticker:string)=>rows.find(s=>s.ticker===ticker)??null;
const formatEps=(v:number|null)=>v===null?"산출 불가":`$${v.toFixed(2)}`;
const formatSignedEps=(v:number|null)=>v===null?"산출 불가":`${v>=0?"+":"-"}$${Math.abs(v).toFixed(2)}`;
const formatMoney=(v:number|null)=>v===null?"산출 불가":Math.abs(v)>=1e9?`$${(v/1e9).toFixed(2)}B`:`$${(v/1e6).toFixed(1)}M`;
const pct=(v:number|null)=>v===null?"산출 불가":`${v>0?"+":""}${v.toFixed(1)}%`;
const yoy=(v:number|null)=>v===null?"YoY 산출 불가":`YoY ${pct(v)}`;
const revision=(v:number|null)=>v===null?"산출 불가":pct(v);
const epsLabels:Record<string,string>={growth:"",profit_turnaround:"흑자 전환",loss_turnaround:"적자 전환",loss_improving:"적자 개선",loss_widening:"적자 확대",unavailable:"YoY 산출 불가"};
const epsYoyText=(s:Snapshot|null)=>{const st=str(s,"eps_yoy_status","epsYoyStatus")??"unavailable";return st==="growth"?yoy(num(s,"eps_yoy_pct","epsYoyPct")):epsLabels[st]??"YoY 산출 불가"};
const epsTone=(s:Snapshot|null)=>{const st=str(s,"eps_yoy_status","epsYoyStatus");return st==="profit_turnaround"||st==="loss_improving"?1:st==="loss_turnaround"||st==="loss_widening"?-1:num(s,"eps_yoy_pct","epsYoyPct")};
const toneClass=(v:number|null)=>v===null?"neutral":v>0?"positive":v<0?"negative":"neutral";
const fy1Eps=(s:Snapshot|null)=>num(s,"annual_fwd_eps_estimate","fy1Eps")??num(s,"annual_fwd_eps_estimate","annualFwdEpsEstimate");
const fy1Change1m=(s:Snapshot|null)=>num(s,"fwd_eps_change_pct","fy1EpsChange1mPct")??num(s,"fwd_eps_change_pct","fwdEpsChangePct");
const fy1Change3m=(s:Snapshot|null)=>num(s,"fy1_eps_change_3m_pct","fy1EpsChange3mPct");
const fy1Label=(s:Snapshot|null)=>{const d=str(s,"estimate_fiscal_date","fy1FiscalDate")??str(s,"estimate_fiscal_date","estimateFiscalDate");return d?`FY${d.slice(0,4)}`:"FY 산출 불가"};
const metric=(s:Snapshot|null,key:string)=>key==="eps_yoy"?num(s,"eps_yoy_pct","epsYoyPct")??-Infinity:key==="revenue_yoy"?num(s,"revenue_yoy_pct","revenueYoyPct")??-Infinity:key==="fy1_1m"?fy1Change1m(s)??-Infinity:fy1Change3m(s)??-Infinity;
const trendText=(s:Snapshot|null)=>{const v=fy1Change3m(s)??fy1Change1m(s);return v===null?"→ 비교값 대기":v>0?"↑ 상향":v<0?"↓ 하향":"→ 유지"};
const fy1Sub=(s:Snapshot|null)=>{const v=fy1Change3m(s);return v===null?"3M 비교값 대기":`3M ${pct(v)}`};
function missingList(v:unknown):string[]{if(Array.isArray(v))return v.filter((x):x is string=>typeof x==="string");if(typeof v!=="string")return[];try{const p=JSON.parse(v);return Array.isArray(p)?p:[]}catch{return[]}}
const originLabel=(p:PilotState)=>p.status==="loading"?"불러오는 중":p.snapshots.length?"LIVE":p.status==="error"?"오류":"데이터 없음";
const snapshotState=(p:PilotState,s:Snapshot|null)=>p.status==="loading"?"불러오는 중":s?"LIVE":p.status==="error"?"오류":"데이터 없음";
const dateTime=(v:string|null)=>v?new Intl.DateTimeFormat("ko-KR",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Seoul"}).format(new Date(v)):"기록 없음";

function LiveBanner({pilot}:{pilot:PilotState}){return <div className="scope-banner"><div><i className={pilot.snapshots.length?"connected":""}/>{originLabel(pilot)}</div><strong>Pilot Universe: 3 / Nasdaq 100</strong><span>{pilot.lastUpdated?`Updated ${dateTime(pilot.lastUpdated)}`:"PLTR · NVDA · MSFT"}</span></div>}
function Heading(p:{eyebrow:string;title:string;description:string;badge:string}){return <div className="page-heading"><div><span>{p.eyebrow}</span><h1>{p.title}</h1><p>{p.description}</p></div><b>{p.badge}</b></div>}
function Panel({eyebrow,title,badge}:{eyebrow:string;title:string;badge:string}){return <header className="structure-panel-header"><div><span>{eyebrow}</span><h2>{title}</h2></div><b>{badge}</b></header>}
function Status({status}:{status:Company["status"]}){return <span className={`structure-status ${status.toLowerCase().replaceAll(" ","-")}`}>{status}</span>}
function MetricCell({value,sub,tone}:{value:string;sub:string;tone:number|null}){return <td className="stacked-metric"><strong>{value}</strong><small className={toneClass(tone)}>{sub}</small></td>}
function ResultCard({label,value,change,period,tone}:{label:string;value:string;change:string;period:string;tone:number|null}){return <article><span>{label}</span><strong>{value}</strong><b className={toneClass(tone)}>{change}</b><small>{period}</small></article>}
function MetricLine({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function DataBadge({pilot,snapshot}:{pilot:PilotState;snapshot:Snapshot|null}){return <span className={`data-origin ${snapshot?"live":pilot.status==="loading"?"loading":"empty"}`}>{snapshot?"LIVE":pilot.status==="loading"?"불러오는 중":pilot.status==="error"?"오류":"데이터 없음"}</span>}
function Info({label,value,note}:{label:string;value:string;note:string}){return <article className="metric-card"><div className="metric-label">{label}</div><div className="metric-value text-value">{value}</div><p>{note}</p></article>}
function Abbr({short,full,ko}:{short:string;full:string;ko:string}){return <span className="abbreviation" title={`${full} · ${ko}`}><b>{short}</b><small>{full}<em>{ko}</em></small></span>}
