"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type View = "Fundamental Overview" | "Screener" | "Company Detail" | "Watchlist" | "Data Pilot";
type Company = { ticker:string; company:string; sector:string; status:"Newly Selected"|"Continuing Improvement"|"Watch"|"Caution"|"Excluded"; reason:string };
const companies: Company[] = [
  {ticker:"MU",company:"Micron Technology",sector:"Technology · Semiconductors",status:"Watch",reason:"3개월 검증 대상 · 경기순환 및 기저효과"},
  {ticker:"TER",company:"Teradyne",sector:"Technology · Semiconductor Equipment",status:"Watch",reason:"3개월 검증 대상 · 반도체 테스트 수요"},
  {ticker:"ALNY",company:"Alnylam Pharmaceuticals",sector:"Health Care · Biotechnology",status:"Watch",reason:"3개월 검증 대상 · 흑자 전환"},
  {ticker:"PLTR",company:"Palantir Technologies",sector:"Technology · Software",status:"Watch",reason:"3개월 검증 대상 · 구조적 성장"},
  {ticker:"NVDA",company:"NVIDIA Corporation",sector:"Technology · Semiconductors",status:"Watch",reason:"3개월 검증 대상 · 대형 성장 및 GAAP 영향"},
];
const icons:Record<View,string>={"Fundamental Overview":"⌂",Screener:"◎","Company Detail":"▤",Watchlist:"☆","Data Pilot":"↻"};

export default function Home(){
  const [view,setView]=useState<View>("Fundamental Overview"); const [ticker,setTicker]=useState("PLTR"); const [mobile,setMobile]=useState(false); const pilot=usePilot();
  const open=(next:string)=>{setTicker(next);setView("Company Detail");setMobile(false)};
  return <main className="structure-shell"><aside className={`main-nav ${mobile?"open":""}`}><div className="nav-brand"><span>F</span><div><strong>Fundamental Flow</strong><small>Investment Philosophy v1.1</small></div></div><nav aria-label="주요 화면">{(Object.keys(icons) as View[]).map(item=><button key={item} className={view===item?"active":""} onClick={()=>{setView(item);setMobile(false)}}><i>{icons[item]}</i><span>{item}</span>{item==="Data Pilot"&&<b>LIVE</b>}</button>)}</nav><div className="nav-philosophy"><span>OUR PHILOSOPHY</span><p>우리는 주가를 추종하지 않는다.<br/><strong>기업의 변화를 추적한다.</strong></p></div><div className="pilot-indicator"><i/> Validation Universe: {companies.length} / Nasdaq 100</div></aside>
    <section className="structure-workspace"><header className="structure-header"><button className="menu-button" onClick={()=>setMobile(!mobile)} aria-label="메뉴 열기">☰</button><div><span>{view}</span><small>Actual Growth · FY1 Consensus</small></div><button className="header-search" onClick={()=>setView("Screener")}>⌕ <span>기업 검색</span></button></header>
      {view==="Fundamental Overview"&&<Dashboard pilot={pilot} open={open}/>} {view==="Screener"&&<Screener/>} {view==="Company Detail"&&<Detail pilot={pilot} ticker={ticker}/>} {view==="Watchlist"&&<Watchlist open={open}/>} {view==="Data Pilot"&&<DataPilot pilot={pilot} open={open}/>}</section>{mobile&&<button className="nav-overlay" aria-label="메뉴 닫기" onClick={()=>setMobile(false)}/>}</main>;
}

function Dashboard({pilot,open}:{pilot:PilotState;open:(t:string)=>void}){
  const cards=[{label:"신규 선정",value:0,tone:"blue"},{label:"지속 개선",value:0,tone:"green"},{label:"관찰",value:companies.length,tone:"amber"},{label:"주의",value:0,tone:"red"},{label:"제외",value:0,tone:"gray"}];
  const trends=fundamentalOverview(pilot.snapshots);
  return <div className="structure-content"><section className="structure-hero philosophy-hero"><div><span>INVESTMENT PHILOSOPHY v1.1</span><h1>우리는 주가를 추종하지 않는다.<br/>기업의 변화를 추적한다.</h1><p>We do not follow stock prices. We follow changes in business fundamentals.</p></div><div className="universe-ring"><strong>{pilot.snapshots.length||companies.length}</strong><span>OBSERVED COMPANIES</span><small>Fundamental Change</small></div></section><LiveBanner pilot={pilot}/>
    <section className="fundamental-trend-section"><div className="section-intro"><span>PRIMARY VIEW</span><h2>Fundamental Change</h2><p>점수보다 기업의 이익 전망, 성장, 수익성, 현금 창출력의 방향을 먼저 봅니다.</p></div><div className="fundamental-trend-grid">{trends.map(item=><article key={item.label}><span>{item.label}</span><strong className={item.tone}>{item.signal}</strong><small>{item.detail}</small></article>)}</div></section>
    <section className="structure-panel change-panel"><Panel eyebrow="COMPANY-BY-COMPANY EXPLANATION" title="기업 변화와 분류 이유" badge={originLabel(pilot)}/><div className="change-company-list">{companies.map(c=>{const s=find(pilot.snapshots,c.ticker);return <button key={c.ticker} onClick={()=>open(c.ticker)}><span className="ticker-avatar">{c.ticker.slice(0,2)}</span><div className="change-company-name"><strong>{c.ticker}</strong><small>{c.company}</small><Status status={c.status}/></div><div className="change-reasons"><b>Reason</b>{fundamentalReasons(s).map(reason=><small key={reason.label} className={reason.tone}>{reason.mark} {reason.label}</small>)}</div><span className={`rule40-state ${rule40State(s).toLowerCase()}`}>Rule of 40 · {rule40State(s)}</span><i>›</i></button>})}</div></section>
    <section className="secondary-screening"><div className="section-intro compact"><span>SECONDARY VIEW</span><h2>Screening Classification</h2><p>분류는 펀더멘털 변화를 요약하는 보조 정보입니다.</p></div><div className="status-card-grid">{cards.map(c=><article key={c.label} className={`status-card ${c.tone}`}><span>{c.label}</span><strong>{c.value}</strong><small>{c.label==="관찰"?"변화 근거 축적 중":"해당 기업 없음"}</small></article>)}</div></section></div>;
}

function Screener(){
  const ranking=useRanking(); const transfer=useCandidateTransfer(); const [query,setQuery]=useState("");
  const visible=useMemo(()=>ranking.rows.filter(row=>`${row.ticker} ${row.name??""}`.toLowerCase().includes(query.toLowerCase())),[query,ranking.rows]);
  return <div className="structure-content"><Heading eyebrow="NASDAQ 100 · PILOT RANKING" title="Screener" description="Nasdaq 100 전체에서 실제 성장과 FY1 컨센서스 변화를 백분위 점수로 비교한 단순 순위입니다. Dashboard 선정 상태에는 반영하지 않습니다." badge="TOP 10"/>
    <section className="ranking-summary"><div><span>수집 범위</span><strong>{ranking.coverage} / 100</strong></div><div><span>현재 점수 단계</span><strong>{rankingStageLabel(ranking.stage)}</strong></div><div><span>마지막 업데이트</span><strong>{dateTime(ranking.lastUpdated)}</strong></div><button onClick={ranking.refresh} disabled={ranking.refreshing}>{ranking.refreshing?`${ranking.progress}% 수집 중…`:"Nasdaq 100 업데이트"}</button></section>
    <p className="ranking-note">{ranking.stage==="actual_only"?"초기 순위: EPS YoY 50% + Revenue YoY 50%. 1개월·3개월 스냅샷이 충분히 쌓이면 FY1 수정률이 자동 반영됩니다.":ranking.stage==="one_month"?"중간 순위: EPS YoY 35% + Revenue YoY 35% + FY1 1M 30%.":"정식 관찰 순위: EPS YoY 30% + Revenue YoY 30% + FY1 1M 20% + FY1 3M 20%."}</p>
    <div className="filter-bar ranking-filter"><label><span>⌕</span><input aria-label="순위 기업 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Top 10 티커 또는 회사명 검색"/></label><span>{visible.length} / 10 companies</span></div>
    <section className="structure-panel screener-table ranking-table"><table><thead><tr><th>순위</th><th>기업</th><th>섹터</th><th>최근 분기 EPS<small className="metric-definition">GAAP diluted <EpsDefinition/></small></th><th>최근 분기 Revenue</th><th>FY1 1M</th><th>FY1 3M</th><th>Fundamental Score</th><th>Buy Engine</th></tr></thead><tbody>{visible.map(row=><RankingCandidateRow key={row.ticker} row={row} send={transfer.send}/>)}</tbody></table>{!visible.length&&<div className="empty-state"><strong>{ranking.refreshing?"Nasdaq 100 데이터를 수집 중입니다.":"순위 데이터가 없습니다."}</strong><span>{ranking.refreshing?`진행률 ${ranking.progress}%`:"Nasdaq 100 업데이트를 실행하면 Top 10이 계산됩니다."}</span></div>}</section></div>;
}

function RankingCandidateRow({row,send}:{row:RankingRow;send:(ticker:string)=>Promise<string>}){
  const [sending,setSending]=useState(false); const [message,setMessage]=useState("");
  const submit=async()=>{setSending(true);setMessage("");try{setMessage(await send(row.ticker))}catch(error){setMessage(error instanceof Error?error.message:"전송 실패")}finally{setSending(false)}};
  return <tr><td><strong className="rank-number">#{row.rank}</strong></td><td><strong>{row.ticker}</strong><small>{row.name}</small></td><td>{row.sector}</td><MetricCell value={formatEps(num(row,"latest_quarter_eps","latestQuarterEps"))} sub={epsYoyText(row)} tone={epsTone(row)}/><MetricCell value={formatMoney(num(row,"latest_quarter_revenue","latestQuarterRevenue"))} sub={yoy(num(row,"revenue_yoy_pct","revenueYoyPct"))} tone={num(row,"revenue_yoy_pct","revenueYoyPct")}/><td className={toneClass(fy1Change1m(row))}>{revision(fy1Change1m(row))}</td><td className={toneClass(fy1Change3m(row))}>{revision(fy1Change3m(row))}</td><td><strong>{row.score.toFixed(1)}</strong><small>백분위 종합</small></td><td><button className="send-buy-button" disabled={sending} onClick={submit}>{sending?"전송 중…":"Add to Buy Engine"}</button>{message&&<small className="send-result">{message}</small>}</td></tr>;
}

function Detail({pilot,ticker}:{pilot:PilotState;ticker:string}){
  const c=companies.find(x=>x.ticker===ticker)??companies[0],s=find(pilot.snapshots,ticker),companyHistory=useCompanyHistory(ticker),transfer=useCandidateTransfer(),history=companyHistory.rows.filter(x=>fy1Eps(x)!==null&&fy1Label(x)===fy1Label(s)).slice().reverse();
  const [sending,setSending]=useState(false),[sendMessage,setSendMessage]=useState("");
  const addCandidate=async()=>{setSending(true);setSendMessage("");try{setSendMessage(await transfer.send(c.ticker))}catch(error){setSendMessage(error instanceof Error?error.message:"전송 실패")}finally{setSending(false)}};
  const period=`${str(s,"latest_fiscal_year","latestFiscalYear")??"—"} ${str(s,"latest_fiscal_period","latestFiscalPeriod")??""}`;
  return <div className="structure-content"><section className="detail-heading"><div className="ticker-avatar large">{c.ticker.slice(0,2)}</div><div><span>{c.sector}</span><h1>{c.company}</h1><p>{c.ticker} · Nasdaq 100 Pilot</p></div><Status status={c.status}/><div className="detail-buy-action"><button className="send-buy-button" disabled={sending||!s} onClick={addCandidate}>{sending?"전송 중…":"Add to Buy Engine"}</button>{sendMessage&&<small>{sendMessage}</small>}</div></section><div className="detail-section-grid">
    <section className="structure-panel wide"><Panel eyebrow="COMPANY PROFILE" title="기업 기본 정보" badge="PILOT"/><div className="profile-grid"><span>티커<strong>{c.ticker}</strong></span><span>회사명<strong>{c.company}</strong></span><span>섹터<strong>{c.sector}</strong></span><span>데이터 상태<strong>{snapshotState(pilot,s)}</strong></span></div></section>
    <section className="structure-panel connected-section wide"><Panel eyebrow="PRIMARY FUNDAMENTAL SIGNALS" title="Core Indicators" badge={s?"LIVE":"데이터 없음"}/><div className="connected-metrics core-indicator-grid"><ResultCard label="Forward EPS" value={formatEps(fy1Eps(s))} change={`${trendText(s)} · 1개월 수정률 ${revision(fy1Change1m(s))}`} period={`${fy1Label(s)} · 3개월 수정률 ${revision(fy1Change3m(s))}`} tone={fy1Change3m(s)??fy1Change1m(s)}/><ResultCard label="Revenue Growth" value={pct(num(s,"revenue_yoy_pct","revenueYoyPct"))} change={fundamentalSignal(num(s,"revenue_yoy_pct","revenueYoyPct"),"성장 유지","성장 둔화")} period={`${period} · YoY`} tone={num(s,"revenue_yoy_pct","revenueYoyPct")}/><ResultCard label="Operating Margin" value={formatRatio(num(s,"operating_margin","operatingMargin"))} change={monthlyComparison(num(s,"operating_margin_change_pp","operatingMarginChangePp"))} period="TTM · 수익성" tone={num(s,"operating_margin_change_pp","operatingMarginChangePp")}/><ResultCard label="Operating Cash Flow" value={formatMoney(num(s,"operating_cash_flow","operatingCashFlow"))} change="월간 비교값 대기" period="TTM · 이익의 현금화" tone={num(s,"operating_cash_flow","operatingCashFlow")}/></div></section>
    <section className="structure-panel connected-section wide"><Panel eyebrow="CONTEXT & VALIDATION" title="Supporting Indicators" badge={`Quality ${snapshotQualityScore(s)??0}%`}/><div className="connected-metrics supporting-indicator-grid"><ResultCard label="CAPEX" value={formatMoney(num(s,"capital_expenditure","capitalExpenditure"))} change="투자 규모" period="TTM" tone={null}/><ResultCard label="Free Cash Flow" value={formatMoney(num(s,"free_cash_flow","freeCashFlow"))} change={fundamentalSignal(num(s,"free_cash_flow","freeCashFlow"),"현금 창출","현금 유출")} period="CFO − CAPEX" tone={num(s,"free_cash_flow","freeCashFlow")}/><article className="validation-result"><span>Rule of 40</span><strong className={rule40State(s).toLowerCase()}>{rule40State(s)}</strong><small>상세 수치는 검증 지표로만 사용</small></article><article className="validation-result"><span>Snapshot Quality</span><strong>{snapshotQualityScore(s)===null?"미평가":`${snapshotQualityScore(s)}%`}</strong><small>{qualityGuidance(s)}</small></article></div></section>
    <section className="structure-panel ai-explanation wide"><Panel eyebrow="RULE-BASED EXPLANATION" title="AI Analysis" badge="설명 전용"/><div><strong>현재 펀더멘털 변화 해석</strong>{aiExplanation(s).map(line=><p key={line}>✓ {line}</p>)}<small>투자 추천이 아닙니다. 확인된 재무 변화만 설명합니다.</small></div></section>
    <section className="structure-panel wide"><Panel eyebrow="SNAPSHOT QUALITY" title="데이터 품질" badge={`${snapshotQualityScore(s)??0}%`}/><div className="profile-grid"><span>Revenue<strong>{qualityCheck(s,"revenue")?"✓":"Missing"}</strong></span><span>Revenue Growth<strong>{qualityCheck(s,"revenueGrowth")?"✓":"Missing"}</strong></span><span>Forward EPS<strong>{qualityCheck(s,"forwardEps")?"✓":"Missing"}</strong></span><span>Operating Margin<strong>{qualityCheck(s,"operatingMargin")?"✓":"Missing"}</strong></span><span>CFO<strong>{qualityCheck(s,"operatingCashFlow")?"✓":"Missing"}</strong></span><span>CAPEX<strong>{qualityCheck(s,"capitalExpenditure")?"✓":"Missing"}</strong></span><span>Fiscal<strong>{qualityCheck(s,"fiscal")?"✓":"Missing"}</strong></span></div><p className="connection-message">{qualityGuidance(s)}</p></section>
    <section className="structure-panel guidance-section wide"><Panel eyebrow="MANAGEMENT INTENT" title="Management Guidance" badge="COMING SOON"/><div className="guidance-grid"><article><span>REVENUE GUIDANCE</span><strong>매출 가이던스</strong><p>경영진이 제시한 매출 전망의 방향과 시장 기대 수준을 분리해 봅니다.</p><div className="guidance-comparisons"><small>이전 경영진 가이던스 대비<b>연결 예정</b></small><small>시장 컨센서스 대비<b>연결 예정</b></small></div></article><article><span>EARNINGS OUTLOOK</span><strong>이익·마진 전망</strong><p>EPS와 영업이익률에 대한 공식 전망을 서로 다른 비교 기준으로 확인합니다.</p><div className="guidance-comparisons"><small>이전 마진 전망 대비<b>연결 예정</b></small><small>시장 EPS 컨센서스 대비<b>연결 예정</b></small></div></article><article><span>CAPITAL ALLOCATION</span><strong>CAPEX 방향</strong><p>투자 확대·유지·축소 여부와 경영진이 설명한 목적을 함께 확인합니다.</p><div className="guidance-comparisons"><small>이전 투자계획 대비<b>연결 예정</b></small><small>FCF 영향 판단<b>연결 예정</b></small></div></article></div><div className="call-ai-preview"><div><span>EARNINGS CALL AI OPINION</span><strong>컨콜 AI 의견</strong></div><p>지난 분기보다 경영진이 더 낙관적인지, 보수적인지 또는 변화가 없는지를 짧게 요약합니다.</p><b>AI 연결 전 · Coming Soon</b></div></section>
    <section className="structure-panel wide"><Panel eyebrow="TIME SERIES" title="Monthly Trends" badge={companyHistory.loading?"불러오는 중":history.length>=2?"LIVE":"준비 중"}/>{history.length>=2?<div className="trend-chart" aria-label="FY1 EPS 월별 추세">{history.map((x,i)=><div key={`${x.ticker}-${i}`} style={{height:`${Math.max(18,(fy1Eps(x)??0)/Math.max(...history.map(h=>fy1Eps(h)??1))*100)}%`}} title={`${str(x,"snapshot_date","snapshotDate")}: ${formatEps(fy1Eps(x))}`}/>)}</div>:<div className="empty-state"><strong>{companyHistory.loading?"스냅샷 이력 불러오는 중":"FY1 EPS 추세 준비 중"}</strong><span>{fy1Label(s)} 기준 최소 2개 유효 월별 스냅샷 필요 · 현재 {history.length}개</span></div>}<SnapshotHistory rows={companyHistory.rows} loading={companyHistory.loading}/></section>
    <section className="structure-panel wide"><Panel eyebrow="CLASSIFICATION" title="Screening Status" badge="준비 중"/><div className="empty-state"><strong>네 가지 핵심 지표 데이터 축적 중</strong><span>EPS YoY · Revenue YoY · FY1 1M · FY1 3M</span></div></section></div>
    <section className="abbreviation-guide"><span>약어 안내</span><Abbr short="EPS" full="Earnings per Share" ko="주당순이익"/><Abbr short="YoY" full="Year over Year" ko="전년 동기 대비"/><Abbr short="FY1" full="Forward Fiscal Year 1" ko="가장 가까운 미래 회계연도"/><Abbr short="FCF" full="Free Cash Flow" ko="잉여현금흐름"/></section></div>;
}

function Watchlist({open}:{open:(t:string)=>void}){return <div className="structure-content"><Heading eyebrow="PERSONAL MONITORING" title="Watchlist" description="저장 기능을 연결하기 전 샘플 관심기업 화면입니다. 실제 포트폴리오가 아닙니다." badge="SAMPLE"/><div className="watchlist-grid">{companies.slice(0,2).map(c=><button key={c.ticker} onClick={()=>open(c.ticker)}><span className="ticker-avatar">{c.ticker.slice(0,2)}</span><div><strong>{c.ticker}</strong><p>{c.company}</p></div><small>SAMPLE · 저장되지 않음</small></button>)}</div></div>}

function DataPilot({pilot,open}:{pilot:PilotState;open:(ticker:string)=>void}){const missing=pilot.snapshots.filter(s=>missingList(read(s,"missing_fields","missingFields")).length).length;return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">F</span><span>Fundamental Flow</span><span className="mvp-badge">FMP PILOT</span></div><span className={`api-pill ${pilot.status}`}><i/>{statusLabel[pilot.status]}</span></header><section className="content"><div className="hero-row"><div><p className="eyebrow">ACTUAL GROWTH · FY1 CONSENSUS</p><h1>재무 데이터 API 파일럿</h1><p className="subtitle">기업별 최신 수집 상태를 관리합니다. 과거 스냅샷은 각 기업의 이력 보기에서 확인합니다.</p></div><button className="sync-button" onClick={pilot.refresh} disabled={pilot.refreshing||pilot.status==="key_missing"}><span className={pilot.refreshing?"spinning":""}>↻</span>{pilot.refreshing?"수집 중…":"지금 업데이트"}</button></div>
    <section className="connection-panel"><div className="connection-main"><span className={`connection-icon ${pilot.snapshots.length?"live":""}`}>{pilot.snapshots.length?"✓":"!"}</span><div><strong>Financial Modeling Prep</strong><p>{statusLabel[pilot.status]} · 서버 측 보안 연결</p></div></div><div className="connection-stat"><span>검증 유니버스</span><strong>{companies.length}개 종목</strong></div><div className="connection-stat"><span>마지막 업데이트</span><strong>{dateTime(pilot.lastUpdated)}</strong></div><div className="connection-stat"><span>데이터 누락</span><strong>{missing}개 기업</strong></div></section>
    {pilot.status==="error"&&<div className="notice-banner"><strong>API 오류</strong><span>마지막 정상 스냅샷: {dateTime(pilot.lastSuccessfulUpdate)}</span></div>}
    <div className="metric-grid compact-metrics"><Info label="실제 EPS" value="GAAP Diluted" note="동일 회계분기 YoY"/><Info label="실제 Revenue" value="Quarterly" note="동일 회계분기 YoY"/><Info label="미래 전망" value="FY1 EPS" note="가장 가까운 미래 회계연도"/><Info label="금액 단위" value="$B / $M" note="달러 단위 일관 표시"/></div>
    <section className="table-card"><div className="result-bar live-result"><div><strong>기업별 최신 스냅샷</strong><span>{originLabel(pilot)}</span></div><span>전체 이력은 기업별로 분리 조회</span></div><div className="table-scroll"><table className="fundamental-table growth-table"><thead><tr><th>기업</th><th>최신 스냅샷</th><th>최근 실적 회계분기</th><th>최근 분기 EPS<small className="metric-definition">GAAP diluted <EpsDefinition/></small></th><th>EPS YoY</th><th>최근 분기 Revenue</th><th>Revenue YoY</th><th>FY1 EPS</th><th>대상 연도</th><th>FY1 1M</th><th>FY1 3M</th><th>품질</th><th>이력</th></tr></thead><tbody>{pilot.snapshots.map(s=><PilotRow key={s.ticker} s={s} open={open}/>)}</tbody></table>{!pilot.snapshots.length&&<div className="empty-state table-empty"><strong>{pilot.status==="loading"?"불러오는 중":"데이터 없음"}</strong><span>LIVE 데이터가 로드된 후에만 값과 성장률을 표시합니다.</span></div>}</div></section>
    <section className="definition-card"><div><span>01</span><strong>Actual EPS</strong><p>FMP GAAP diluted EPS, 동일 회계분기 비교</p></div><div><span>02</span><strong>Revenue YoY</strong><p>최근 분기와 전년 동일 분기의 매출 비교</p></div><div><span>03</span><strong>FY1 EPS</strong><p>현재 이후 가장 가까운 회계연도의 annual epsAvg</p></div><div><span>04</span><strong>Revisions</strong><p>동일 FY1 대상 연도의 1개월·3개월 저장값과 비교</p></div></section></section></main>}

function PilotRow({s,open}:{s:Snapshot;open:(ticker:string)=>void}){const quality=snapshotQualityScore(s);return <tr><td><div className="company-cell"><span className="ticker">{s.ticker}</span><strong>{companies.find(c=>c.ticker===s.ticker)?.company}</strong></div></td><td>{str(s,"snapshot_date","snapshotDate")??"—"}</td><td>{`${str(s,"latest_fiscal_year","latestFiscalYear")??"—"} ${str(s,"latest_fiscal_period","latestFiscalPeriod")??""}`}</td><td>{formatEps(num(s,"latest_quarter_eps","latestQuarterEps"))}</td><td className={toneClass(epsTone(s))}>{epsYoyText(s)}</td><td>{formatMoney(num(s,"latest_quarter_revenue","latestQuarterRevenue"))}</td><td className={toneClass(num(s,"revenue_yoy_pct","revenueYoyPct"))}>{yoy(num(s,"revenue_yoy_pct","revenueYoyPct"))}</td><td>{formatEps(fy1Eps(s))}</td><td>{fy1Label(s)}</td><td>{revision(fy1Change1m(s))}</td><td>{revision(fy1Change3m(s))}</td><td><span className={`quality-badge ${(quality??0)<80?"partial":"complete"}`}>{quality===null?"미평가":`${quality}%`}</span></td><td><button className="history-button" onClick={()=>open(s.ticker)} aria-label={`${s.ticker} 스냅샷 이력 보기`}>이력 보기 ›</button></td></tr>}

type ApiStatus="loading"|"connected"|"partial"|"key_missing"|"database_error"|"database_unavailable"|"error";
type Snapshot={ticker:string;[key:string]:unknown};
type RankingRow=Snapshot&{rank:number;score:number;name?:string;sector?:string};
type RankingStage="actual_only"|"one_month"|"three_month";
type PilotState={status:ApiStatus;snapshots:Snapshot[];history:Snapshot[];lastUpdated:string|null;lastSuccessfulUpdate:string|null;refreshing:boolean;refresh:()=>Promise<void>};
const statusLabel:Record<ApiStatus,string>={loading:"불러오는 중",connected:"LIVE",partial:"LIVE · 일부 산출 불가",key_missing:"API 키 필요",database_error:"오류",database_unavailable:"데이터 없음",error:"오류"};

function usePilot():PilotState{const [status,setStatus]=useState<ApiStatus>("loading"),[snapshots,setSnapshots]=useState<Snapshot[]>([]),[history,setHistory]=useState<Snapshot[]>([]),[lastUpdated,setLastUpdated]=useState<string|null>(null),[lastSuccessfulUpdate,setLastSuccessful]=useState<string|null>(null),[refreshing,setRefreshing]=useState(false);const load=useCallback(async()=>{try{const r=await fetch("/api/fundamentals",{cache:"no-store"}),p=await r.json();setStatus((p.status as ApiStatus)||(r.ok?"connected":"error"));setSnapshots(Array.isArray(p.snapshots)?p.snapshots:[]);setHistory(Array.isArray(p.history)?p.history:[]);setLastUpdated(p.lastUpdated??null);setLastSuccessful(p.lastSuccessfulUpdate??null)}catch{setStatus("error")}},[]);useEffect(()=>{queueMicrotask(()=>void load())},[load]);const refresh=useCallback(async()=>{setRefreshing(true);try{const r=await fetch("/api/fundamentals",{method:"POST"}),p=await r.json();setStatus((p.status as ApiStatus)||(r.ok?"connected":"error"));if(Array.isArray(p.results))setSnapshots(p.results);setLastUpdated(p.lastUpdated??null);await load()}catch{setStatus("error")}finally{setRefreshing(false)}},[load]);return{status,snapshots,history,lastUpdated,lastSuccessfulUpdate,refreshing,refresh}}

function useCompanyHistory(ticker:string){const [state,setState]=useState<{ticker:string;rows:Snapshot[]}>({ticker:"",rows:[]});useEffect(()=>{let active=true;fetch(`/api/fundamentals?ticker=${encodeURIComponent(ticker)}`,{cache:"no-store"}).then(r=>r.json()).then(p=>{if(active)setState({ticker,rows:Array.isArray(p.history)?p.history:[]})}).catch(()=>{if(active)setState({ticker,rows:[]})});return()=>{active=false}},[ticker]);return{rows:state.ticker===ticker?state.rows:[],loading:state.ticker!==ticker}}

function useRanking(){const [rows,setRows]=useState<RankingRow[]>([]),[coverage,setCoverage]=useState(0),[stage,setStage]=useState<RankingStage>("actual_only"),[lastUpdated,setLastUpdated]=useState<string|null>(null),[refreshing,setRefreshing]=useState(false),[progress,setProgress]=useState(0);const load=useCallback(async()=>{try{const r=await fetch("/api/rankings",{cache:"no-store"}),p=await r.json();setRows(Array.isArray(p.rankings)?p.rankings:[]);setCoverage(typeof p.coverage==="number"?p.coverage:0);setStage(p.stage==="three_month"||p.stage==="one_month"?p.stage:"actual_only");setLastUpdated(p.lastUpdated??null)}catch{setRows([])}},[]);useEffect(()=>{queueMicrotask(()=>void load())},[load]);const refresh=useCallback(async()=>{setRefreshing(true);setProgress(0);try{const response=await fetch("/api/rankings",{method:"POST"});if(!response.ok)throw new Error("Ranking collection failed");setProgress(100);await load()}finally{setRefreshing(false)}},[load]);return{rows,coverage,stage,lastUpdated,refreshing,progress,refresh}}

function useCandidateTransfer(){const send=useCallback(async(ticker:string)=>{const destination=window.open("about:blank","_blank");if(destination)destination.opener=null;try{const response=await fetch("/api/buy-engine/candidates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticker})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Buy Engine으로 전송하지 못했습니다.");if(typeof payload.importUrl!=="string")throw new Error("Buy Engine 전달 링크를 만들지 못했습니다.");if(destination)destination.location.replace(payload.importUrl);else window.location.assign(payload.importUrl);return "새 탭의 Buy Engine에서 후보 등록을 처리합니다."}catch(error){destination?.close();throw error}},[]);return{send}}

function SnapshotHistory({rows,loading}:{rows:Snapshot[];loading:boolean}){return <div className="snapshot-history"><div className="history-heading"><div><span>SNAPSHOT HISTORY</span><strong>저장 이력</strong></div><b>{loading?"불러오는 중":`${rows.length}개 기록`}</b></div>{!loading&&rows.length?<div className="history-scroll"><table><thead><tr><th>저장일</th><th>대상 연도</th><th>FY1 EPS</th><th>1M 수정률</th><th>3M 수정률</th><th>최근 분기 EPS YoY</th><th>Revenue YoY</th><th>품질</th></tr></thead><tbody>{rows.map((row,index)=>{const quality=snapshotQualityScore(row);return <tr key={`${str(row,"snapshot_date","snapshotDate")}-${index}`}><td>{str(row,"snapshot_date","snapshotDate")??"—"}</td><td>{fy1Label(row)}</td><td>{formatEps(fy1Eps(row))}</td><td>{revision(fy1Change1m(row))}</td><td>{revision(fy1Change3m(row))}</td><td className={toneClass(epsTone(row))}>{epsYoyText(row)}</td><td className={toneClass(num(row,"revenue_yoy_pct","revenueYoyPct"))}>{yoy(num(row,"revenue_yoy_pct","revenueYoyPct"))}</td><td><span className={`quality-badge ${(quality??0)<80?"partial":"complete"}`}>{quality===null?"미평가":`${quality}%`}</span></td></tr>})}</tbody></table></div>:!loading?<div className="empty-state"><strong>저장된 스냅샷이 없습니다.</strong><span>Data Pilot에서 업데이트하면 날짜별로 저장됩니다.</span></div>:null}</div>}

const read=(s:Snapshot|null,a:string,b:string)=>s?.[a]??s?.[b]??null;
const num=(s:Snapshot|null,a:string,b:string)=>{const v=read(s,a,b);return typeof v==="number"?v:null};
const str=(s:Snapshot|null,a:string,b:string)=>{const v=read(s,a,b);return typeof v==="string"?v:null};
const find=(rows:Snapshot[],ticker:string)=>rows.find(s=>s.ticker===ticker)??null;
const formatEps=(v:number|null)=>v===null?"산출 불가":`$${v.toFixed(2)}`;
const formatSignedEps=(v:number|null)=>v===null?"산출 불가":`${v>=0?"+":"-"}$${Math.abs(v).toFixed(2)}`;
const formatMoney=(v:number|null)=>v===null?"산출 불가":Math.abs(v)>=1e9?`$${(v/1e9).toFixed(2)}B`:`$${(v/1e6).toFixed(1)}M`;
const pct=(v:number|null)=>v===null?"산출 불가":`${v>0?"+":""}${v.toFixed(1)}%`;
const yoy=(v:number|null)=>v===null?"YoY 산출 불가":`YoY ${pct(v)}`;
const revision=(v:number|null)=>v===null?"산출 불가":pct(v);
const epsLabels:Record<string,string>={growth:"",profit_turnaround:"흑자 전환",loss_turnaround:"적자 전환",loss_improving:"적자 개선",loss_widening:"적자 확대",unavailable:"YoY 산출 불가"};
const epsYoyText=(s:Snapshot|null)=>{const st=str(s,"eps_yoy_status","epsYoyStatus")??"unavailable";return st==="growth"?yoy(num(s,"eps_yoy_pct","epsYoyPct")):epsLabels[st]??"YoY 산출 불가"};
const epsTone=(s:Snapshot|null)=>{const st=str(s,"eps_yoy_status","epsYoyStatus");return st==="profit_turnaround"||st==="loss_improving"?1:st==="loss_turnaround"||st==="loss_widening"?-1:num(s,"eps_yoy_pct","epsYoyPct")};
const toneClass=(v:number|null)=>v===null?"neutral":v>0?"positive":v<0?"negative":"neutral";
const fy1Eps=(s:Snapshot|null)=>num(s,"annual_fwd_eps_estimate","fy1Eps")??num(s,"annual_fwd_eps_estimate","annualFwdEpsEstimate");
const fy1Change1m=(s:Snapshot|null)=>num(s,"fwd_eps_change_pct","fy1EpsChange1mPct")??num(s,"fwd_eps_change_pct","fwdEpsChangePct");
const fy1Change3m=(s:Snapshot|null)=>num(s,"fy1_eps_change_3m_pct","fy1EpsChange3mPct");
const fy1Label=(s:Snapshot|null)=>{const d=str(s,"estimate_fiscal_date","fy1FiscalDate")??str(s,"estimate_fiscal_date","estimateFiscalDate");return d?`FY${d.slice(0,4)}`:"FY 산출 불가"};
const snapshotQualityScore=(s:Snapshot|null)=>num(s,"snapshot_quality_score","snapshotQualityScore")??(typeof s?.snapshotQuality==="object"&&s.snapshotQuality!==null&&typeof (s.snapshotQuality as {score?:unknown}).score==="number"?(s.snapshotQuality as {score:number}).score:null);
function qualityChecks(s:Snapshot|null):Record<string,boolean>{const raw=read(s,"snapshot_quality_checks","snapshotQualityChecks")??(typeof s?.snapshotQuality==="object"&&s.snapshotQuality!==null?(s.snapshotQuality as {checks?:unknown}).checks:null);if(raw&&typeof raw==="object"&&!Array.isArray(raw))return raw as Record<string,boolean>;if(typeof raw!=="string")return{};try{const parsed=JSON.parse(raw);return parsed&&typeof parsed==="object"?parsed:{}}catch{return{}}}
const qualityCheck=(s:Snapshot|null,key:string)=>qualityChecks(s)[key]===true;
const qualityGuidance=(s:Snapshot|null)=>{const score=snapshotQualityScore(s);return score===null?"품질 평가 전입니다.":score<80?`Quality ${score}: 누락 데이터가 있어 AI 판단의 확신 수준을 낮춰야 합니다.`:`Quality ${score}: 규칙 기반 AI 분석에 사용할 수 있는 품질입니다.`};
const trendText=(s:Snapshot|null)=>{const v=fy1Change3m(s)??fy1Change1m(s);return v===null?"→ 비교값 대기":v>0?"↑ 상향":v<0?"↓ 하향":"→ 유지"};
const formatRatio=(v:number|null)=>v===null?"산출 불가":`${(v*100).toFixed(1)}%`;
const fundamentalSignal=(v:number|null,positive:string,negative:string)=>v===null?"비교값 대기":v>0?positive:v<0?negative:"변화 없음";
const monthlyComparison=(v:number|null)=>v===null?"월간 비교값 대기":v>0?`전월 대비 +${v.toFixed(1)}%p`:v<0?`전월 대비 ${v.toFixed(1)}%p`:"전월 대비 유지";
const rule40State=(s:Snapshot|null)=>{const value=num(s,"classic_rule_40","classicRule40");return value!==null&&value>=40?"PASS":"WARNING"};
function fundamentalReasons(s:Snapshot|null){
  if(!s)return[{label:"실데이터 수집 대기",mark:"·",tone:"neutral"}];
  const forward=fy1Change3m(s)??fy1Change1m(s),growth=num(s,"revenue_yoy_pct","revenueYoyPct"),marginChange=num(s,"operating_margin_change_pp","operatingMarginChangePp"),cfo=num(s,"operating_cash_flow","operatingCashFlow");
  return [
    {label:forward===null?"Forward EPS 비교값 대기":forward>0?"Forward EPS 개선":"Forward EPS 약화",mark:forward===null?"·":forward>=0?"✓":"!",tone:toneClass(forward)},
    {label:growth===null?"Revenue Growth 산출 대기":growth>0?"Revenue Growth 유지":"Revenue Growth 둔화",mark:growth===null?"·":growth>=0?"✓":"!",tone:toneClass(growth)},
    {label:marginChange===null?"Operating Margin 비교값 대기":marginChange>=0?"Operating Margin 안정":"Operating Margin 약화",mark:marginChange===null?"·":marginChange>=0?"✓":"!",tone:toneClass(marginChange)},
    {label:cfo===null?"Operating Cash Flow 산출 대기":cfo>=0?"Operating Cash Flow 확인":"Operating Cash Flow 음수",mark:cfo===null?"·":cfo>=0?"✓":"!",tone:toneClass(cfo)},
  ];
}
function fundamentalOverview(rows:Snapshot[]){
  const valid=rows.filter(Boolean),forward=valid.map(s=>fy1Change3m(s)??fy1Change1m(s)).filter((v):v is number=>v!==null),growth=valid.map(s=>num(s,"revenue_yoy_pct","revenueYoyPct")).filter((v):v is number=>v!==null),margins=valid.map(s=>num(s,"operating_margin_change_pp","operatingMarginChangePp")).filter((v):v is number=>v!==null),cash=valid.map(s=>num(s,"operating_cash_flow","operatingCashFlow")).filter((v):v is number=>v!==null);
  const direction=(values:number[],positive:string,negative:string)=>values.length===0?{signal:"비교값 대기",detail:"월별 Snapshot 축적 필요",tone:"neutral"}:{signal:values.filter(v=>v>0).length>=values.filter(v=>v<0).length?positive:negative,detail:`${values.length}개 유효 기업 기준`,tone:values.reduce((a,b)=>a+b,0)>=0?"positive":"negative"};
  return [
    {label:"Forward EPS Trend",...direction(forward,"상향 우세","하향 우세")},
    {label:"Revenue Growth Trend",...direction(growth,"성장 우세","둔화 우세")},
    {label:"Operating Margin Trend",...direction(margins,"개선 우세","약화 우세")},
    {label:"Operating Cash Flow Trend",...direction(cash,"현금 창출 우세","현금 유출 우세")},
  ];
}
function aiExplanation(s:Snapshot|null){
  if(!s)return["분석 가능한 Snapshot을 기다리고 있습니다."];
  const lines:string[]=[]; const forward=fy1Change3m(s)??fy1Change1m(s),growth=num(s,"revenue_yoy_pct","revenueYoyPct"),margin=num(s,"operating_margin","operatingMargin"),cfo=num(s,"operating_cash_flow","operatingCashFlow"),fcf=num(s,"free_cash_flow","freeCashFlow"),capex=num(s,"capital_expenditure","capitalExpenditure");
  lines.push(forward===null?"Forward EPS는 비교 이력이 더 필요합니다.":forward>=0?"Forward EPS가 유지되거나 개선되고 있습니다.":"Forward EPS가 이전 Snapshot보다 약화되었습니다.");
  lines.push(growth===null?"Revenue Growth를 산출할 수 없습니다.":growth>=0?"Revenue Growth가 플러스 성장을 유지합니다.":"Revenue Growth가 전년 동기보다 감소했습니다.");
  lines.push(margin===null?"Operating Margin 확인이 필요합니다.":margin>=0?"Operating Margin이 플러스를 유지합니다.":"Operating Margin이 마이너스입니다.");
  lines.push(cfo===null?"Operating Cash Flow 확인이 필요합니다.":cfo>=0?"Operating Cash Flow가 이익의 현금화를 뒷받침합니다.":"Operating Cash Flow가 음수여서 이익의 현금화 확인이 필요합니다.");
  if(fcf!==null&&fcf<0&&capex!==null&&capex>0)lines.push("Free Cash Flow 감소에는 CAPEX 투자의 영향이 포함되어 있습니다.");
  lines.push(snapshotQualityScore(s)!==null&&(snapshotQualityScore(s)??0)>=80?"현재 Snapshot은 규칙 기반 투자 논리 검토에 사용할 수 있습니다.":"데이터 품질이 낮아 투자 논리 판단에 주의가 필요합니다.");
  return lines;
}
function missingList(v:unknown):string[]{if(Array.isArray(v))return v.filter((x):x is string=>typeof x==="string");if(typeof v!=="string")return[];try{const p=JSON.parse(v);return Array.isArray(p)?p:[]}catch{return[]}}
const originLabel=(p:PilotState)=>p.status==="loading"?"불러오는 중":p.snapshots.length?"LIVE":p.status==="error"?"오류":"데이터 없음";
const snapshotState=(p:PilotState,s:Snapshot|null)=>p.status==="loading"?"불러오는 중":s?"LIVE":p.status==="error"?"오류":"데이터 없음";
const dateTime=(v:string|null)=>v?new Intl.DateTimeFormat("ko-KR",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Seoul"}).format(new Date(v)):"기록 없음";
const rankingStageLabel=(stage:RankingStage)=>stage==="three_month"?"4개 지표 · 3M 포함":stage==="one_month"?"3개 지표 · 1M 포함":"실제 성장 · 잠정";

function LiveBanner({pilot}:{pilot:PilotState}){return <div className="scope-banner"><div><i className={pilot.snapshots.length?"connected":""}/>{originLabel(pilot)}</div><strong>Validation Universe: {companies.length} / Nasdaq 100</strong><span>{pilot.lastUpdated?`Updated ${dateTime(pilot.lastUpdated)}`:companies.map(company=>company.ticker).join(" · ")}</span></div>}
function Heading(p:{eyebrow:string;title:string;description:string;badge:string}){return <div className="page-heading"><div><span>{p.eyebrow}</span><h1>{p.title}</h1><p>{p.description}</p></div><b>{p.badge}</b></div>}
function Panel({eyebrow,title,badge}:{eyebrow:string;title:string;badge:string}){return <header className="structure-panel-header"><div><span>{eyebrow}</span><h2>{title}</h2></div><b>{badge}</b></header>}
function Status({status}:{status:Company["status"]}){return <span className={`structure-status ${status.toLowerCase().replaceAll(" ","-")}`}>{status}</span>}
function MetricCell({value,sub,tone}:{value:string;sub:string;tone:number|null}){return <td className="stacked-metric"><strong>{value}</strong><small className={toneClass(tone)}>{sub}</small></td>}
function ResultCard({label,value,change,period,tone,epsBasis=false}:{label:string;value:string;change:string;period:string;tone:number|null;epsBasis?:boolean}){return <article><span>{label}{epsBasis&&<small className="metric-definition">GAAP diluted <EpsDefinition/></small>}</span><strong>{value}</strong><b className={toneClass(tone)}>{change}</b><small>{period}</small></article>}
function MetricLine({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Info({label,value,note}:{label:string;value:string;note:string}){return <article className="metric-card"><div className="metric-label">{label}</div><div className="metric-value text-value">{value}</div><p>{note}</p></article>}
function Abbr({short,full,ko}:{short:string;full:string;ko:string}){return <span className="abbreviation" title={`${full} · ${ko}`}><b>{short}</b><small>{full}<em>{ko}</em></small></span>}
function EpsDefinition(){return <span className="metric-help" tabIndex={0} role="note" aria-label="GAAP diluted EPS 설명">?<span>미국 회계기준에 따른 희석 주당순이익입니다. 잠재 주식의 희석 효과를 반영하며 Non-GAAP EPS와 구분됩니다.</span></span>}
